# Generated by Django 3.2.2 on 2021-05-30 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='adult',
        ),
    ]
