# Generated by Django 3.2.2 on 2021-05-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movie_adult'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='adult',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
