# Generated by Django 3.2.2 on 2021-05-20 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMovie',
        ),
    ]
