# Generated by Django 3.2.2 on 2021-05-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
